config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'meetings/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  resources :photos, only: %i[index show new create destroy]

  resources :meetings, only: :index

  resources :activities

  resources :chatrooms, only: :index do
    resources :messages, only: :create
  end

  match "*path", to: "errors#not_found", via: :all
  get '/500', to: 'errors#internal_server'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home_nav.html.erb
<div class="home-navbar">
  <% if user_signed_in? %>
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= inline_svg_tag "icons/logo.svg" %>
      <%= inline_svg_tag "icons/text-logo.svg" %>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= inline_svg_tag "icons/logo.svg" %>
      <%= inline_svg_tag "icons/text-logo.svg" %>
    <% end %>
  <% end %>

  <div>
    <ul class="home-nav-right me-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "card-headers" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, class: "card-headers", data: {turbo_method: :delete} %>
        </li>
      <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "card-headers" %>
          <%= link_to "Login", new_user_session_path, class: "card-headers" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navsidebar.html.erb
<div class="navbar">
  <div class="logo-container">
    <%= link_to root_path do %>
      <%= inline_svg_tag "icons/logo.svg" %>
    <% end %>
  </div>

  <div class="menu-container">
    <div class="nav-item align-middle">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <% if current_page?(dashboard_path) %>
            <%= inline_svg_tag "icons/home-black.svg" %>
        <% else %>
          <%= inline_svg_tag "icons/home.svg" %>
        <% end %>
      <% end %>
    </div>

    <div class="nav-item align-middle">
      <%= link_to chatrooms_path, class: "nav-link" do %>
        <% if current_page?(chatrooms_path) %>
            <%= inline_svg_tag "icons/messages-black.svg" %>
        <%  else %>
          <%= inline_svg_tag "icons/messages.svg" %>
        <% end %>
      <% end %>
    </div>

    <div class="nav-item align-middle">
      <%= link_to photos_path, class: "nav-link" do %>
        <% if current_page?(photos_path) %>
            <%= inline_svg_tag "icons/galery-black.svg" %>
        <% else %>
          <%= inline_svg_tag "icons/galery.svg" %>
        <% end %>
      <% end %>
    </div>

    <div class="nav-item align-middle">
      <%= link_to activities_path, class: "nav-link" do %>
        <% if current_page?(activities_path) %>
            <%= inline_svg_tag "icons/activities-black.svg" %>
        <% else %>
          <%= inline_svg_tag "icons/activities.svg" %>
        <% end %>
      <% end %>
    </div>

    <div class="nav-item align-middle">
      <%= link_to meetings_path, class: "nav-link" do %>
      <% if current_page?(meetings_path) %>
          <%= inline_svg_tag "icons/calendar-black.svg" %>
        <% else %>
          <%= inline_svg_tag "icons/calendar.svg" %>
        <% end %>
      <% end %>
    </div>

    <%# <div class="nav-item align-middle"> %>
      <%# link_to root_path, class: "nav-link" do %>
      <%# inline_svg_tag "icons/settings.svg" %>
      <%# end %>
    <%# </div> %>

    <div class="nav-item align-middle">
    <%= button_to destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "nav-button" do %>
      <%= inline_svg_tag "icons/sign-out.svg" %>
    <% end %>
    </div>
  </div>

</div>